# Generated by Django 4.2.25 on 2025-11-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
